// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp7t_YtRSJg109NP8o0owYFtFWVxpuWNI',
    appId: '1:623164754910:web:df5b970481f0974a08eb4f',
    messagingSenderId: '623164754910',
    projectId: 'sports-app-ed2c0',
    authDomain: 'sports-app-ed2c0.firebaseapp.com',
    storageBucket: 'sports-app-ed2c0.appspot.com',
    measurementId: 'G-RQEPJSJSQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRzWEw0xUNRgY4thZAUb6ZHiYBN1EMvk',
    appId: '1:623164754910:android:420d4469cc15e3b108eb4f',
    messagingSenderId: '623164754910',
    projectId: 'sports-app-ed2c0',
    storageBucket: 'sports-app-ed2c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWx5bxDgUpBUUh79wZTBVu7r2V9Ns7_zQ',
    appId: '1:623164754910:ios:1837173dd0be218908eb4f',
    messagingSenderId: '623164754910',
    projectId: 'sports-app-ed2c0',
    storageBucket: 'sports-app-ed2c0.appspot.com',
    iosClientId: '623164754910-sal79tjv54gbaonlveuoa7o11o8if6ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWx5bxDgUpBUUh79wZTBVu7r2V9Ns7_zQ',
    appId: '1:623164754910:ios:6ee897798e13fd9c08eb4f',
    messagingSenderId: '623164754910',
    projectId: 'sports-app-ed2c0',
    storageBucket: 'sports-app-ed2c0.appspot.com',
    iosClientId: '623164754910-q8urcfn3publsgva9qknuh35mtg1kv7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
